# Site settings
baseurl = "http://example.org/"
languageCode = "en-US"
title = "Simple FAQ Theme for Hugo"
theme = "hugo-faq-theme"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

# Menu
SectionPagesMenu = "main"

	[[menu.main]]
		name = "Basics"
		weight = 10
		url = "#basics"
	[[menu.main]]
		name = "Mobile"
		weight = 20
		url = "#mobile"
	[[menu.main]]
		name = "Account"
		weight = 30
		url = "#account"
	[[menu.main]]
		name = "Payments"
		weight = 40
		url = "#payments"
	[[menu.main]]
		name = "Privacy"
		weight = 50
		url = "#privacy"
	[[menu.main]]
		name = "Delivery"
		weight = 60
		url = "#delivery"

[params]
	
	# Custom styling
	# To customize the styling of this theme, uncomment and edit the following line to point 
	# to your site's css in the assets/ directory. 

	custom_css = ["css/blue.css"]